from uuid import uuid4

from pydantic import UUID4
from sqlalchemy import delete
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlmodel import select

from models.database import get_session
from models.models import to_model
from models.task import (
    Task,
    TaskCreate,
    TaskRead,
    TaskReadParticipant,
)
from models.task_config.task_config import TaskConfig
from models.task_participant import TaskParticipant, TaskParticipantRead
from models.task_response import TaskResponse
from models.user import User
from services.logging import get_logger

logger = get_logger(__name__)


async def create_task(task_create: TaskCreate) -> TaskRead:
    task = Task(
        id=uuid4(), **task_create.model_dump(), public=task_create.config.public
    )
    async with get_session() as session:
        session.add(task)
        await session.commit()
        await session.refresh(task)
    return to_model(task, TaskRead)


async def delete_task(task_id: UUID4):
    query = delete(Task).where(Task.id == task_id)  # type: ignore
    async with get_session() as session:
        await session.execute(query)
        await session.commit()


async def get_task(
    task_id: UUID4, user_id: UUID4
) -> tuple[TaskReadParticipant | None, bool]:
    """
    A user is authorized to to access a task if they are one of the task's participants
    Returns 2-tuple:
    1. `Task`: the task exists
       `None`: the task does not exist
    2. `True`: the user is authorized
       `False`: the doesn't exist or the user is unauthorized
    """
    logger.debug(f"Getting task {task_id} for user {user_id}")
    query = (
        select(
            Task,
            TaskParticipant.user_id,
            TaskResponse,
        )
        .outerjoin(
            TaskParticipant,
            (Task.id == TaskParticipant.task_id) & (TaskParticipant.user_id == user_id),  # type: ignore
        )
        .outerjoin(
            TaskResponse, (Task.id == task_id) & (TaskResponse.user_id == user_id)
        )  # type: ignore
        .where(Task.id == task_id)
    )

    async with get_session() as session:
        result: tuple[Task, UUID4 | None, TaskResponse | None] = (
            await session.execute(query)
        ).first()

        if not result:
            logger.debug(f"Task {task_id} not found")
            return None, True
        task, is_participant, completed = result
        task.config = TaskConfig.model_validate(task.config)
        logger.debug(f"Task {task_id} found")
        if task.config.public and not is_participant:
            logger.debug(f"Adding user {user_id} to task {task_id}")
            await session.execute(
                pg_insert(User)
                .values(**User(id=user_id, autogenerated=True).model_dump())
                .on_conflict_do_nothing()
            )
            session.add(TaskParticipant(task_id=task_id, user_id=user_id))
            await session.commit()
            is_participant = True
        await session.refresh(task)
        return TaskReadParticipant(
            id=task.id, config=task.config, completed=bool(completed)
        ), bool(is_participant)


async def get_task_participants(task_id: UUID4) -> list[TaskParticipantRead]:
    query = (
        select(TaskParticipant, TaskResponse)
        .outerjoin(
            TaskResponse,
            (TaskParticipant.task_id == task_id) & (TaskResponse.task == task_id),  # type: ignore
        )
        .where(TaskParticipant.task_id == task_id)
    )
    async with get_session() as session:
        results: list[tuple[TaskParticipant, TaskResponse]] = (
            await session.execute(query)
        ).all()
    return [
        TaskParticipantRead(task_id=tp.task_id, user_id=tp.user_id, completed=bool(tr))
        for tp, tr in results
    ]
